name: Build and Release PDFs

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile English LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/the-globe-1614.latex

      - name: Compile Swedish LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/the-globe-1614-sv.latex

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload PDF files to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: the-globe-1614.pdf
          asset_name: the-globe-1614.pdf
          asset_content_type: application/pdf

      - name: Upload Swedish PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: the-globe-1614-sv.pdf
          asset_name: the-globe-1614-sv.pdf
          asset_content_type: application/pdf
